name: wechat deployment

on:
  workflow_dispatch:
  push:
    branches: [ wechat-release, whatsapp-release ]

env:
  REPO_URL: https://github.com/quboqin/wechaty-chatgpt.git
  REPO_BRANCH: release  
  PADLOCAL_TOKEN: ${{ secrets.PADLOCAL_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  FLAG_STUDIO_KEY: ${{ secrets.FLAG_STUDIO_KEY }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  PUPPETEER_LAUNCH_COMMAND: ${{ secrets.PUPPETEER_LAUNCH_COMMAND }}

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Set env for wechat
      run: |
        echo "PROJECT_NAME=wechat" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/branches/wechat-release')

    - name: Set env for whatsapp
      run: |
        echo "PROJECT_NAME=whatsapp" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/branches/whatsapp-release')

    - name: deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        envs: REPO_URL,REPO_BRANCH,PADLOCAL_TOKEN,OPENAI_API_KEY,FLAG_STUDIO_KEY,DISCORD_TOKEN,PUPPETEER_LAUNCH_COMMAND,PROJECT_NAME
        timeout: 300s
        script: |
          pm2 stop --silent $PROJECT_NAME
          rm -rf $PROJECT_NAME
          git clone $REPO_URL -b $REPO_BRANCH $PROJECT_NAME
          cd $PROJECT_NAME
          touch .env
          echo PADLOCAL_TOKEN=$PADLOCAL_TOKEN >> .env
          echo OPENAI_API_KEY=$OPENAI_API_KEY >> .env
          echo FLAG_STUDIO_KEY=$FLAG_STUDIO_KEY >> .env
          echo DISCORD_TOKEN=$DISCORD_TOKEN >> .env
          echo PUPPETEER_LAUNCH_COMMAND=$PUPPETEER_LAUNCH_COMMAND >> .env
          npm i
          pm2 start src/$PROJECT_NAME.js --name $PROJECT_NAME