name: chatgpt bot deployment

on:
  workflow_dispatch:
  push:
    branches: [ wechat-release, whatsapp-release, telegram-release ]

env:
  REPO_URL: https://github.com/quboqin/wechaty-chatgpt.git
  REPO_BRANCH: ${{ github.head_ref || github.ref_name }}
  PADLOCAL_TOKEN: ${{ secrets.PADLOCAL_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  FLAG_STUDIO_KEY: ${{ secrets.FLAG_STUDIO_KEY }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  WECHAT_HOST: ${{ secrets.WECHAT_HOST }}
  WHATSAPP_HOST: ${{ secrets.WHATSAPP_HOST }}
  TELEGRAM_HOST: ${{ secrets.TELEGRAM_HOST }}
  PUPPETEER: prod

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: set project name
      run: |
        echo "PROJECT_NAME=`echo $REPO_BRANCH | sed 's/-release//g'`" >> $GITHUB_ENV

    - name: select host
      run: |
        echo "HOST=`echo $"$PROJECT_NAME"_HOST`" >> $GITHUB_ENV    

    - name: deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: $HOST
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        envs: REPO_URL,REPO_BRANCH,PADLOCAL_TOKEN,OPENAI_API_KEY,FLAG_STUDIO_KEY,DISCORD_TOKEN,PUPPETEER,PROJECT_NAME
        timeout: 300s
        script: |
          pm2 stop --silent $PROJECT_NAME
          rm -rf $PROJECT_NAME
          git clone $REPO_URL -b $REPO_BRANCH $PROJECT_NAME
          cd $PROJECT_NAME
          touch .env
          echo PADLOCAL_TOKEN=$PADLOCAL_TOKEN >> .env
          echo OPENAI_API_KEY=$OPENAI_API_KEY >> .env
          echo FLAG_STUDIO_KEY=$FLAG_STUDIO_KEY >> .env
          echo DISCORD_TOKEN=$DISCORD_TOKEN >> .env
          echo PUPPETEER=$PUPPETEER >> .env
          npm i
          pm2 start src/$PROJECT_NAME.js --name $PROJECT_NAME